// <auto-generated />
using System;
using Entity.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entity.Migrations.PostgreSql
{
    [DbContext(typeof(ApplicationDbContextPostgreSql))]
    partial class ApplicationDbContextPostgreSqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<int>("BPM")
                        .HasColumnType("integer");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TabNotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TuningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TuningId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            BPM = 140,
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Name = "Alternate Picking en 3 cuerdas",
                            TabNotation = "E|----------------|\r\nB|----------------|\r\nG|--0-2-4-2-0-----|\r\nD|--0-2-4-2-0-----|\r\nA|----------------|\r\nE|----------------|",
                            TuningId = 1
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            BPM = 120,
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Name = "Legato básico en escala menor",
                            TabNotation = "E|----------------|\r\nB|----------------|\r\nG|--5h7p5---------|\r\nD|-------7h9p7----|\r\nA|----------------|\r\nE|----------------|",
                            TuningId = 1
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            BPM = 160,
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Name = "Sweep en arpegio mayor",
                            TabNotation = "E|------12p8------|\r\nB|----10-----10----|\r\nG|--9---------9----|\r\nD|-----------------|\r\nA|-----------------|\r\nE|-----------------|",
                            TuningId = 2
                        },
                        new
                        {
                            Id = 4,
                            Asset = true,
                            BPM = 180,
                            Difficulty = "Expert",
                            IsDeleted = false,
                            Name = "Alternate Picking avanzado",
                            TabNotation = "E|--0-1-2-3-4--0-1-2-3-4--|\r\nB|------------------------|\r\nG|------------------------|\r\nD|------------------------|\r\nA|------------------------|\r\nE|------------------------|",
                            TuningId = 1
                        },
                        new
                        {
                            Id = 5,
                            Asset = true,
                            BPM = 150,
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Name = "Legato rápido con saltos",
                            TabNotation = "E|--7h9p7--9h11p9--|\r\nB|------------------|\r\nG|--6h8p6-----------|\r\nD|------------------|\r\nA|------------------|\r\nE|------------------|",
                            TuningId = 1
                        });
                });

            modelBuilder.Entity("Entity.Models.Guitarist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guitarists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            ExperienceYears = 5,
                            IsDeleted = false,
                            Name = "Aníbal Alvarado Andrade",
                            SkillLevel = "Advanced"
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            ExperienceYears = 1,
                            IsDeleted = false,
                            Name = "Brayan Stiven Carvajal",
                            SkillLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            ExperienceYears = 1,
                            IsDeleted = false,
                            Name = "Diego Fernando Cuellar",
                            SkillLevel = "Beginner"
                        });
                });

            modelBuilder.Entity("Entity.Models.GuitaristLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<int>("GuitaristId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuitaristId");

                    b.HasIndex("LessonId");

                    b.ToTable("GuitaristLessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            GuitaristId = 1,
                            IsDeleted = false,
                            LessonId = 1,
                            ProgressPercent = 100.0,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            GuitaristId = 1,
                            IsDeleted = false,
                            LessonId = 2,
                            ProgressPercent = 60.0,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            GuitaristId = 2,
                            IsDeleted = false,
                            LessonId = 1,
                            ProgressPercent = 40.0,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 4,
                            Asset = true,
                            GuitaristId = 2,
                            IsDeleted = false,
                            LessonId = 3,
                            ProgressPercent = 0.0,
                            Status = "NotStarted"
                        },
                        new
                        {
                            Id = 5,
                            Asset = true,
                            GuitaristId = 3,
                            IsDeleted = false,
                            LessonId = 2,
                            ProgressPercent = 0.0,
                            Status = "NotStarted"
                        });
                });

            modelBuilder.Entity("Entity.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            Description = "Serie de ejercicios para dominar el picking alternado a alta velocidad.",
                            IsDeleted = false,
                            Name = "Dominando Alternate Picking",
                            TechniqueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            Description = "Ejercicios de legato centrados en patrones menores y modales.",
                            IsDeleted = false,
                            Name = "Legato en escalas menores",
                            TechniqueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            Description = "Práctica de arpegios mayores con técnica de sweep.",
                            IsDeleted = false,
                            Name = "Sweep Arpegios Mayores",
                            TechniqueId = 3
                        });
                });

            modelBuilder.Entity("Entity.Models.LessonExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            ExerciseId = 1,
                            IsDeleted = false,
                            LessonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            ExerciseId = 4,
                            IsDeleted = false,
                            LessonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            ExerciseId = 2,
                            IsDeleted = false,
                            LessonId = 2
                        },
                        new
                        {
                            Id = 4,
                            Asset = true,
                            ExerciseId = 5,
                            IsDeleted = false,
                            LessonId = 2
                        },
                        new
                        {
                            Id = 5,
                            Asset = true,
                            ExerciseId = 3,
                            IsDeleted = false,
                            LessonId = 3
                        });
                });

            modelBuilder.Entity("Entity.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Entity.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Techniques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            Description = "Movimientos alternados de púa para mejorar velocidad y precisión.",
                            IsDeleted = false,
                            Name = "Alternate Picking"
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            Description = "Técnica centrada en hammer-ons y pull-offs para lograr fluidez.",
                            IsDeleted = false,
                            Name = "Legato"
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            Description = "Desplazamientos continuos de púa a través de cuerdas para ejecutar arpegios rápidos.",
                            IsDeleted = false,
                            Name = "Sweep Picking"
                        });
                });

            modelBuilder.Entity("Entity.Models.Tuning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tunings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            IsDeleted = false,
                            Name = "Standard E",
                            Notes = "E A D G B E"
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            IsDeleted = false,
                            Name = "Drop D",
                            Notes = "D A D G B E"
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            IsDeleted = false,
                            Name = "C Standard",
                            Notes = "C F A# D# G C"
                        });
                });

            modelBuilder.Entity("Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuitaristId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuitaristId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            Email = "anibalalvaradoandrade@gmail.com",
                            GuitaristId = 1,
                            IsDeleted = false,
                            Password = "$2a$12$tWJFKE5AxcI22akEUprqMuJoQ0QXLUbAg4FRklLYTQQc1dGCv1AlW",
                            Username = "anibal25"
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            Email = "carva@gmail.com",
                            GuitaristId = 2,
                            IsDeleted = false,
                            Password = "$2a$12$AyTpx8lEKlO9F9ltw5b8j.hGYJ44gK5pFL.ATJNYshNP6PswzOpPa",
                            Username = "carvaInsane"
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            Email = "viego@gmail.com",
                            GuitaristId = 3,
                            IsDeleted = false,
                            Password = "$2a$12$qq6J.RdSq1OTx8hLUGI5huNP9eL.zwD/Ev0QA2ZJ6W3z1YBW0Yo4W",
                            Username = "viego"
                        });
                });

            modelBuilder.Entity("Entity.Models.Exercise", b =>
                {
                    b.HasOne("Entity.Models.Tuning", "Tuning")
                        .WithMany("Exercises")
                        .HasForeignKey("TuningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tuning");
                });

            modelBuilder.Entity("Entity.Models.GuitaristLesson", b =>
                {
                    b.HasOne("Entity.Models.Guitarist", "Guitarist")
                        .WithMany("GuitaristLessons")
                        .HasForeignKey("GuitaristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Lesson", "Lesson")
                        .WithMany("GuitaristLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guitarist");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Entity.Models.Lesson", b =>
                {
                    b.HasOne("Entity.Models.Technique", "Technique")
                        .WithMany("Lessons")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("Entity.Models.LessonExercise", b =>
                {
                    b.HasOne("Entity.Models.Exercise", "Exercise")
                        .WithMany("LessonExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Lesson", "Lesson")
                        .WithMany("LessonExercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Entity.Models.User", b =>
                {
                    b.HasOne("Entity.Models.Guitarist", "Guitarist")
                        .WithMany()
                        .HasForeignKey("GuitaristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guitarist");
                });

            modelBuilder.Entity("Entity.Models.Exercise", b =>
                {
                    b.Navigation("LessonExercises");
                });

            modelBuilder.Entity("Entity.Models.Guitarist", b =>
                {
                    b.Navigation("GuitaristLessons");
                });

            modelBuilder.Entity("Entity.Models.Lesson", b =>
                {
                    b.Navigation("GuitaristLessons");

                    b.Navigation("LessonExercises");
                });

            modelBuilder.Entity("Entity.Models.Technique", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Entity.Models.Tuning", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
